github-aws-runners/terraform-aws-github-runner

modules/runners/main.tf
Custom name was not used in tag.
=> Enable custom names for ec instances

README.md, main.tf, variables.tf
* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution.
N/A
The current situation is that the module doesn't allow overriding the instance type, the change adds a variable to the module so that this can be achieved.
N/A
N/A
Setting the `instance_type` module argument should yield a change in the module's `aws_launch_template` `runner` resource.
- Add the …
=> Add ability to override instance_type

README.md, main.tf, modules/runners/README.md, modules/runners/scale-up.tf, modules/runners/variables.tf, variables.tf
I'm providing this PR to fix https://github.com/philips-labs/terraform-aws-github-runner/issues/51. It just fixes a typo in a variable name. It also fixes the descriptions of two other variables.
- Renamed variable 'runners_maxiumum_count' as 'runners_maximum_count'
- Fixed descriptions of runners_scale_down and runners_scale_up variables
- Renamed variable 'runners_maxiumum_count' as 'runners_maximum_count'. 
- Fixed descriptions of runners_scale_down and runners_scale_up variables
=> Rename variable and fix variables descriptions

README.md
Fix documentation for downloading lambdas
- Fix documentation for downloading lambdas
=> Fix documentation for downloading lambdas

.ci/build.sh
* Running `.ci/build.sh` fails after the first module run as the root directory is a relative path. Fixed by making the root directory an absolute path.
* Fixed incorrect runners lambda path.
=> Fix the build script not entering all the module directories

modules/runner-binaries-syncer/policies/lambda-cloudwatch.json, modules/runners/policies/lambda-cloudwatch.json, modules/webhook/policies/lambda-cloudwatch.json
Recently tried deploying v0.4.0 version of this module. None of the lambdas can log because the resource restriction stops log events from being created on log streams.
=> Add wildcard for log events in arbitrary streams

modules/runners/lambdas/runners/src/lambda.ts
This should show full SQS message details rather than having `attributes` of a record show as `Object`
=> Use console.dir for higher logging depth

modules/runners/policies/lambda-scale-down.json, modules/runners/policies/lambda-scale-up.json
Scaling lambda IAM roles permit tagging and termination of arbitrary EC2 instances, which is not desirable.
Harden scaling lambda IAM policies to ensure we can only tag and terminate _runner_ instances by:
- Scoping `ec2:CreateTags` to just instance creation
- Disallowing `ec2:DeleteTags` (seems to be unused anyways)
- Allowing `ec2:TerminateInstances` for only tagged runner instances
N/A
N/A
This was tested by deploying the runner stack to an AWS account, and having the lambdas scale runners up and down, both of which _seem_ to have succeeded without errors (looking at lambda logs and EC2 instance states).
-  Only allow tagging and termination of runner EC2 instances
=> Only allow tagging and termination of runner instances

modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
=> Fix pagination with listing self-hosted runners

CHANGELOG.md, examples/ubuntu/README.md, examples/ubuntu/lambdas-download/main.tf, examples/ubuntu/main.tf, examples/ubuntu/outputs.tf, examples/ubuntu/providers.tf, examples/ubuntu/templates/user-data.sh, examples/ubuntu/variables.tf, examples/ubuntu/vpc.tf, main.tf, modules/runners/main.tf, modules/runners/variables.tf, variables.tf
At Smartly.io, we want to use runners that largely reflect the hosted Ubuntu runners provided by Github, running on larger instances in AWS. We build internal AMIs based on similar packer configuration to https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu1804.json (and use some of the provisioning scripts from that repository).
This PR exposes the interfaces necessary to hook those custom AMIs into the terraform module, while maintaining the previous default behaviour of using Amazon linux images.
Example use:
```
module "github-runner" {
source  = "./modules/github-runner"
userdata_template = "./templates/user-data.sh"
ami_owners = ["self"]
ami_filter = {
name = ["myorg/github-actions-runner/ubuntu-18.04-*"]
}
block_device_mappings = {
device_name = "/dev/sda1" …
```
=> Provide hooks for using alternate runner os

main.tf, modules/runner-binaries-syncer/runner-binaries-syncer.tf, modules/runner-binaries-syncer/variables.tf, modules/runners/scale-down.tf, modules/runners/scale-up.tf, modules/runners/variables.tf, modules/webhook/variables.tf, modules/webhook/webhook.tf, variables.tf
Submitting a small change to expand the options for sourcing the lambda functions to include S3. Using an S3 bucket would be an alternative to providing local files directly and providing the bucket itself would be up to the user.
We found that a change like this is personally better for our workflow and could be useful for others too. Thanks for the great work on this project!
=> expand options for sourcing lambda to include S3

main.tf, modules/runners/policies-runner.tf, modules/runners/variables.tf, variables.tf
For https://github.com/philips-labs/terraform-aws-github-runner/issues/308. Policies can be managed outside of this stack, or within this stack like so:
```
resource "aws_iam_policy" "my_policy" {
...
}
module "runners" {
...
runner_iam_role_managed_policy_arns = [
aws_iam_policy.my_policy.arn,
]
}
```
Tested by running a `plan` on an existing stack, with and without the list of managed policies.
=> Allow operator to pass in a list of managed IAM policy ARNs for the runner role

modules/runners/logging.tf, modules/runners/policies-runner.tf, modules/runners/policies/instance-cloudwatch-policy.json
Policies for runner insance are missing to write to logstrea, read from parameter store and write metrics.
Fix #388
=> bugfix: Add policies for logging

modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Currently the runner scales in any workflow on the repo is in the status queued. Woudl be less resource wasting to scale only for the event received from SQS based on the status of the check run event.
fix #14
=> fix: scale only if check run is in status queued. #14

.ci/Dockerfile
This should allow the `.ci/build` script to cache the `zip` installation layer between builds hopefully improving the build times slightly when starting fresh :smile:
=> copy directory *after* installing zip

main.tf
* AWS SQS queue visibility times have to be >= the timeout of the associated lambda: [source](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html)
* error to do so will result in a terraform provisioning error during initial resource creation of `module.runners.module.runners.aws_lambda_event_source_mapping.scale_up`:
```bash
terraform apply
...
module.runners.module.runners.aws_lambda_event_source_mapping.scale_up: Still creating... [4m20s elapsed]
module.runners.module.runners.aws_lambda_event_source_mapping.scale_up: Still creating... [4m30s elapsed]
module.runners.module.runners.aws_lambda_event_source_mapping.scale_up: Still creating... [4m40s elapsed]
module.runners.module.runners.aws_lambda_event_source_mapping.scale_up: Still …
```
=> Queue visibility time has to be >= lambda timeout

modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts, modules/webhook/lambdas/webhook/src/webhook/handler.ts
tl;dr Make it possible to reuse one GitHub App for multiple mostly indeoendent environments in combination with ordinary web hooks
If multiple mostly independent groups like to share the same GitHub App for their organizations (different installation ids), but like to use isolated environments of the AWS GitHub Runner, they face a problem as a GitHub App can only have one single webhook and secret configured - independent on how many orgs have installed it.
As the different runner installations have different secrets and different endpoints, one solution would be to just install the App in the org but then register an org or repository webhook that listens on the `check_run` event and point it to the address of the corresponding AWS API endpoint. However - ordinary webhook payloads do not …
=> Retrieve installation id automatically if not present (triggered by ordinary webhook)

.pre-commit-config.yaml, examples/default/vpc.tf, examples/ubuntu/vpc.tf, modules/download-lambda/README.md
Creating the vpc results in the following error:
```
Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service
```
Upgrade vpc module is solving the issue.
=> fix: broken vpc module in examples

modules/runners/main.tf
Found that we had limits that required tags on volumes.     Adding this allowed our instances to start creating.
=> Tag Volume Resources

main.tf
The top-level module is currently not passing `runner_group_name` to the `runners` module.
=> Pass runner_group_name forward

README.md, main.tf, variables.tf
In order to be able to use on_demand runners
=> Allow setting the market_options runners module value

.github/workflows/auto-approve-dependabot.yml
Due to changes in github permisson model run the PR's for dependabot on base
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
=> fix: dependabot approve

examples/ubuntu/providers.tf
This is to fix Issue #658 and is my first PR to this project. Some extra icing: update to `required_providers` post-Terraform 0.13, to squelch Terraform warnings. Thanks for this project and for applying 'Good First Issues' tags. I look forward to the PR review. :)
Note that while I did run `terraform validate` (and the code throws errors unrelated to my change), I didn't have the opportunity to run apply because of this error:
```
❯ terraform validate
Error: Invalid value for module argument
on main.tf line 52, in module "runners":
52:   runner_log_files = [
53:     {
54:       "file_path" : "/var/log/user-data.log",
55:       "log_stream_name" : "{instance_id}/user_data"
56:     },
57:     {
58:       "file_path" : "/home/runners/actions-runner/_diag/Runner_**.log",
59: …
```
=> Create version constraint on Random, and also move to 'required_providers' (post-Terraform 0.13 change).

.ci/Dockerfile, .ci/build.sh
Improves dockerfile / .ci/build.sh script to output lambda zips in a
central location as well as adds buildkit caching to the docker build so
that you don't have to re-download the node_modules of each zip directly
each time you build with .ci/build.sh
This also makes improvements in that if there are only changes in one
directory then the cache will remain and the remaining lambdas will not
be re-built.
I guess an open question as well should be if there should be an additional github actions wofklow added to this?
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
=> .ci: Improve dockerfile to include caching

.gitignore, README.md, examples/ubuntu/main.tf, examples/ubuntu/providers.tf, examples/ubuntu/templates/user-data.sh
When testing the Ubuntu example I ran into a few small issues. To resolve these I have slightly updated the docs and as well added some core dependencies in this example that allows others to use the ubuntu example without having issues running workflows that utilize commonly used actions.
=> Improve readme

README.md
The way to configure subscribing to the `check_run` events on GitHub has apparently changed. It is now under the "Permissions & Events" section:
=> Update Webhook check_run Event Subscription Docs

README.md
=> chore: Fix variable name in readme

examples/ubuntu/main.tf
Unlike RHEL and CentOS, Ubuntu writes logs to `/var/log/syslog` instead of to `/var/log/messages`. This might have been different in the past.
This fixes #783.
=> fix: change Ubuntu example to log syslog instead of messages

modules/runners/lambdas/runners/package.json, modules/runners/lambdas/runners/yarn.lock
Runner module borken since PR https://github.com/philips-labs/terraform-aws-github-runner/commit/d7f9cd74fe22a617b25cdba5781344519b0984e1
Simply downgrade octokit/rest is not fxing the issue, therefore revert back.
=> fix: revert dependency updates on runner module

modules/download-lambda/main.tf
Currently output zip file contains text "404 Not found" and `terraform apply` reports success
Closes #838
=> Make module lambda-download fail when wrong tag is set

main.tf, modules/runners/main.tf, modules/runners/variables.tf, variables.tf
=> variable "volume_size" #830

modules/runners/lambdas/runners/src/scale-runners/runners.test.ts, modules/runners/lambdas/runners/src/scale-runners/runners.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
- Consolidating "is org level runner" logic
- Defining `runnerType` and `runnerOwner`
=> fix(scale): Refactor Runner Type and Owner

main.tf, modules/runners/lambdas/runners/src/scale-runners/runners.test.ts, modules/runners/lambdas/runners/src/scale-runners/runners.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts, modules/runners/main.tf, modules/runners/scale-up.tf, modules/runners/variables.tf, outputs.tf, variables.tf
This PR adds support for multiple spot instance types.
- Creates a launch template for each type
- Set the default template version to `$LATEST`
Changes from #871 merged to this branch. That PR needs to be merged first.
=> Support Multiple Instance Types

README.md, modules/runner-binaries-syncer/README.md, modules/runner-binaries-syncer/variables.tf, modules/runners/README.md, modules/runners/variables.tf, variables.tf
=> docs: fix lambda_security_group_ids incorrect description #738

README.md, main.tf, modules/webhook/README.md, modules/webhook/lambdas/webhook/src/webhook/handler.test.ts, modules/webhook/lambdas/webhook/src/webhook/handler.ts, modules/webhook/variables.tf, modules/webhook/webhook.tf, variables.tf
Add the ability to set a white list of repositories that are allowed to use the the runners.
When creating the github app, github provides two choices: public or private. If an organisation wants to use the github app between multiple organisations they would have to make it public. In that case it would be more secure to have a filtering on which repositories are allowed to use it.
Add an environment variable to the webhook lambda which contains a list of repository full names that are allowed to be processed. The filtering is done on the webhook level at the time of receiving events.
The changes are backward compatible
Signed-off-by: ravenolf <benahmed@soramitsu.co.jp>
=> Add support for white listing of repositories

README.md
Org level admin permissions for the app are not required any more, removed from docs.
=> chore(doc): Remove org level admin permission #801

modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/lambda.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock, modules/runners/lambdas/runners/package.json, modules/runners/lambdas/runners/src/lambda.ts, modules/runners/lambdas/runners/yarn.lock, modules/webhook/lambdas/webhook/package.json, modules/webhook/lambdas/webhook/src/lambda.ts, modules/webhook/lambdas/webhook/src/webhook/handler.test.ts, modules/webhook/lambdas/webhook/src/webhook/handler.ts, modules/webhook/lambdas/webhook/yarn.lock
Upgrades @vercel/ncc to its latest release and updated the code to compile as well.
this should fix #982 and possibly #980
=> bugfix: change module exports and upgrade vercel to latest release

modules/runners/policies-runner.tf, modules/runners/policies/instance-ssm-policy.json
Runner allows to enable SSM manager for debugging purpose. To reduce the parameters can be read from SSM the default permission is replaces by a custom one without granting access to all parameters.
=> fix: reduce permissions required for session manager

modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/handler.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
Checked [alternatives](https://nodesource.com/blog/express-going-into-maintenance-mode) and decided that node-fetch is suitable for our purpose; lowest footprint, no dependencies, supports streaming, heavily used, low number of bugs.
Implementation note: await the success of **_both_** promises before reporting that it was successfully uploaded to S3 (previous implementation did not do that).
=> chore: replace 'request' dependency by 'node-fetch' (#903)

modules/runners/lambdas/runners/package.json, modules/runners/lambdas/runners/src/scale-runners/gh-auth.test.ts, modules/runners/lambdas/runners/src/scale-runners/gh-auth.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts, modules/runners/lambdas/runners/src/scale-runners/ssm.test.ts, modules/runners/lambdas/runners/yarn.lock, modules/webhook/lambdas/webhook/src/ssm/index.test.ts
The newer version of the library requires different input data for yyy in the createAppAuth(xxx)(yyy) function, and also returns a different data structure for the 'app' and 'installation' scenarios.
- Set dependency to version 3.6.0
- Fix some (misleading) test descriptions
=> chore: Bump oktokit/auth-app (#904)

main.tf, modules/runners/main.tf, modules/runners/variables.tf, variables.tf
Proposed code changes to accommodate custom default egress rules, as discussed under issue #748.
Inspired by the GitLab runners code as mentioned under that issue.
Early feedback on these changes is most welcome!
Also, terraform-docs on my end seems to change a lot of the formatting in the README.md files. Am I missing or not doing something obvious? It adds a lot of HTML tags in each line in the tables, hyperlinking to the resources I guess. I'd have thought such formatting should already be present in the current files.
=> current value turned to default under new variable, for issue #748

modules/runners/templates/install-config-runner.sh
Agents stall when running in af-south-1 unless the region is set explicitly: 
```
aws s3 cp s3://default-dist-xxxxx1245/actions-runner-linux.tar.gz .
download failed: s3://default-dist-xxxxx1245/actions-runner-linux.tar.gz to ./actions-runner-linux.tar.gz An error occurred (IllegalLocationConstraintException) when calling the GetObject operation: The af-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.
[root@ip-10-165-0-77 bin]# aws s3 cp s3://default-dist-xxxxx1245/actions-runner-linux.tar.gz . --region af-south-1
download: s3://default-dist-xxxxx1245/actions-runner-linux.tar.gz to ./actions-runner-linux.tar.gz
```
=> Support af-south-1 region

modules/runners/main.tf
Currently, if `market_options` is set to `null`, then Terraform will continuously detect a diff for the launch template configuration and recreate it. This change will use a `dynamic` block to exclude the  `instance_market_options` block entirely if `market_options` is set to `null`.
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
=> fix(runner): use dynamic block to ignore null market opts

README.md, modules/runners/README.md, modules/runners/main.tf, modules/runners/scale-up.tf, modules/runners/variables.tf, variables.tf
Fixes #1152 
Note that pre-commit updated the readme's and appears to have deleted some sections. Am I running an out of date `terraform_docs` or is there a misconfiguration somewhere?
Cheers!
=> Changes `instance_types` from a Set to a List, so instance order preference is preserved

modules/runners/lambdas/runners/src/scale-runners/gh-auth.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Improved logging for scaling up and down behavior.
=> fix: added more detailed logging for scaling up and down

main.tf, variables.tf
Fixes #953
Set the default to 1 day because jobs can be queued for 24 hours then are cancelled by github.
=> feat: adding message retention seconds

main.tf, modules/runners/main.tf, modules/runners/variables.tf, variables.tf
Fixes: https://github.com/philips-labs/terraform-aws-github-runner/issues/1308
need to test it
=> feat: adding var for tags for ec2 instances

README.md, examples/default/main.tf, main.tf, modules/runner-binaries-syncer/README.md, modules/runner-binaries-syncer/main.tf, modules/runner-binaries-syncer/variables.tf, variables.tf
solves #1320 
I took a battle-tested implementation from https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/main.tf#L198
example usage:
KMS SSE
```
...
runner_binaries_s3_sse_configuration = {
rule = {
apply_server_side_encryption_by_default = {
kms_master_key_id = aws_kms_key.dist.arn
sse_algorithm     = "aws:kms"
}
}
}
...
resource "aws_kms_key" "dist" {
description             = "KMS key for dist bucket SES"
deletion_window_in_days = 10
key_usage               = "ENCRYPT_DECRYPT"
enable_key_rotation     = true
is_enabled              = true
policy                  = data.aws_iam_policy_document.allow_kms.json
}
```
S3 SSE
```
runner_binaries_s3_sse_configuration = {
rule = {
apply_server_side_encryption_by_default = {
sse_algorithm     = "AES256"
}
}
}
```
the …
=> feat: dist bucket SSE config

modules/webhook/lambdas/webhook/src/lambda.ts, modules/webhook/lambdas/webhook/src/local.ts, modules/webhook/lambdas/webhook/src/webhook/handler.test.ts, modules/webhook/lambdas/webhook/src/webhook/handler.ts
Replaced several response codes:
- 201: for jobs that are queued
- 202: for jobs that are ignored, also details to body added
fix #1348
=> fix: update return codes, no error code for job that are ignored

README.md, modules/runners/lambdas/runners/src/scale-runners/gh-auth.ts
Fixes: https://github.com/philips-labs/terraform-aws-github-runner/issues/1341
Replace literal `\n` chars with new lines so once the base64 string is decoded the value can a single line string or a multiline string
**Rationale**
1. Single line variables are easier to deal with in GitHub Actions in multiple ways
2. As pointed out in the issue this logic is being applied to the Terraform GitHub provider and so it would be cool if the 2 projects aligned given they are a natural fit
Regex tested against Javascript in https://regex101.com/
EDIT I need to deploy this on my end to check it works as expected as I am not familiar with Typescript unless you can see it will work as is.
=> feat: support single line private keys

examples/default/variables.tf, examples/ubuntu/variables.tf
Clean up unused variables in examples to avoid the examples are not working.
=> fix: clean up non used variables in examples

.github/workflows/lambda-runners.yml, modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
Test set for GH public in module runners, `src/scale-runners/scale-up.test.ts` cannot run in isolation. As full test suite all tests are PASSING, running a test in isolation for the set GH Public results in failures. In CI we run the full set.
Problem is that several mocks are only loaded for GHES cases, which are loaded first. Moving the mockes one level up (suite level), ensures mocks are loaded always.
=> chore: Ensure mockes are always loaded so tests can run in isolation

modules/webhook/lambdas/webhook/src/webhook/handler.ts, modules/webhook/lambdas/webhook/src/webhook/logger.ts
- Move metadata to JSON object for more structured logging
- Add additional detail to logs
- Use supportedEvents list to quickly exit if not supported
Closes #1369
=> fix(logging): Add context to webhook logs

examples/ubuntu/templates/user-data.sh
https://github.com/philips-labs/terraform-aws-github-runner/commit/060daac3568cd36f8b203d3f77f736df7aefb223#diff-e9624b388e62ca51cf1fe073eb0919588e8c36a1143ecdb49580996a89f13beb
https://github.com/philips-labs/terraform-aws-github-runner/commit/060daac3568cd36f8b203d3f77f736df7aefb223#r61361220
I believe this was forgotten to be changed in ubuntu example
Afrer upgrading I got for the ubuntu userdata.sh this:
```
│ Invalid value for "vars" parameter: vars map does not contain key "install_config_runner", referenced at ./templates/user-data.sh.tpl:74,3-24.
╵
```
=> fix install_config_runner -> install_runner

README.md, docs/test-lambda-local.md, main.tf, modules/runner-binaries-syncer/README.md, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/README.md, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/lambda.test.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/lambda.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/local.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/logger.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/modules.d.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/template.yaml, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock, modules/runner-binaries-syncer/runner-binaries-syncer.tf, modules/runner-binaries-syncer/variables.tf, variables.tf
For testing purpose it is convenient to run code locally, for running lambda there is no guidance available. In this PR
- Added a general guide to run lambda locally
- Add setup for runner-binary-syncer
=> chore: Add guide for running lambda locally

README.md, main.tf
Add t4g to the list of arm64 instance types.
=> Support t4g Graviton instance type

README.md
Prevous jobs for self-hosted runners failing immediatly if no potential runner was available. This is changed, jobs will kept queued for 24 hours. This removed the need to create first an offline runner to allow scaling back to zero. (https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow)
=> docs: Offline runners are not required anymore.

modules/runners/pool/main.tf
if the pool list has more than 1 element, terraform cannot apply
It will throw errors like
```sh
Error: Error adding new Lambda Permission for github-pool: ResourceConflictException: The statement id (AllowExecutionFromCloudWatch) provided already exists. Please provide a new statement id, or remove the existing statement.
{
RespMetadata: {
StatusCode: 409,
RequestID: "1baaaa63-a167-49a1-9eb4-e07f824a85ce"
},
Message_: "The statement id (AllowExecutionFromCloudWatch) provided already exists. Please provide a new statement id, or remove the existing statement.",
Type: "User"
```
=> fix(runnrs): Pool runners to allow multiple event rules and targets

images/linux-amzn2/github_agent.linux.pkr.hcl, modules/runners/templates/install-runner.sh
👋 , I wish to use your packer hcl however it needs more variables to be usable in my env:
1. SGs that are open to 0.0.0.0/0 are a big no no so I added a var to allow the SG to be passed in allowing for a more restrictive SG to be created up front. If no SG var is set then null results in the default behaviour of creating a temp SG (as happens now). Added additional vars needed for placing the builder and setting the instance type.
2. Seperated the version from the url for better readability and to perhaps allow for this to be bumped by renovate automatically later.
3. Fixed the permission denied errors raised in https://github.com/philips-labs/terraform-aws-github-runner/issues/1610. /opt and everything in it are owned by root root and so mkdir won't work without sudo and then a …
=> feat(packer): add vars and minor clean up

README.md
Refer to a dedicated channel for the runners
=> chore(docs): refer to dedicate channel for the runners

modules/webhook/lambdas/webhook/.prettierrc, modules/webhook/lambdas/webhook/package.json, modules/webhook/lambdas/webhook/src/lambda.test.ts, modules/webhook/lambdas/webhook/src/lambda.ts, modules/webhook/lambdas/webhook/src/local.ts, modules/webhook/lambdas/webhook/src/sqs/index.test.ts, modules/webhook/lambdas/webhook/src/sqs/index.ts, modules/webhook/lambdas/webhook/src/ssm/index.test.ts, modules/webhook/lambdas/webhook/src/webhook/handler.test.ts, modules/webhook/lambdas/webhook/src/webhook/handler.ts, modules/webhook/lambdas/webhook/yarn.lock
- order typescript import
- add prettier plugin to automatically format plugin order
- replaces importing mocked from ts-jest/utils by jest-mock
=> chore(webhook): depcrated warning on ts-jest mocked

examples/ephemeral/main.tf, examples/prebuilt/variables.tf, examples/ubuntu/main.tf
- Updated AMI filter to select the latest instead of the latest in 2012
- Add commented examples for AMI and ephemeral to ubuntu example
=> fix(examples): Update AMI filter

modules/runners/outputs.tf, outputs.tf
I would like the AMI to be output so I can expose it in a pipeline
=> feat: Add output image id used in launch template

images/linux-amzn2/github_agent.linux.pkr.hcl, images/ubuntu-focal/github_agent.ubuntu.pkr.hcl, images/windows-core-2019/github_agent.windows.pkr.hcl
Issue: #1745
Variablize delete_on_termination for EBS volume.
Make default as true (which make more sense to delete volumes
as they are no longer used by runners).
Fixes: https://github.com/philips-labs/terraform-aws-github-runner/issues/1745
https://www.packer.io/plugins/builders/amazon/ebs#delete_on_termination
By default packer use delete_on_termination set to false.
> [delete_on_termination](https://www.packer.io/plugins/builders/amazon/ebs#delete_on_termination) (bool) - Indicates whether the EBS volume is deleted on instance termination. Default false. NOTE: If this value is not explicitly set to true and volumes are not cleaned up by an alternative method, additional volumes will accumulate after every build.
=> feat: Variablize delete_on_termination

README.md
While running ephemeral runners, check_run does not work and it is not mentioned anywhere in documentation.
2022-02-17 08:43:10.319  WARN [scale-runners:5c3d74d9-1321-5f45-81rd-2e51281e7b3f index.js:113840  Runtime.handler] Ignoring error: The event type check_run is not supported in combination with ephemeral runners.Please ensure you have enabled workflow_job events. 
{}
=> fix: Doc update ephemeral runners need workflow_job

modules/runner-binaries-syncer/runner-binaries-syncer.tf
[source_hash](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object#source_hash) - (Optional) Triggers updates like etag but useful to address etag encryption limitations. Set using filemd5("path/to/source") (Terraform 0.11.12 or later). (The value is only stored in state and not saved by AWS.)
source_hash should help eliminate some "plan drifts" that are caused when using KMS encryption and etag together
it shouldn't affect the functionality if not using SSE KMS on the bucket.
=> fix: Use source_hash instead of etag to prevent drift when using KMS

images/linux-amzn2/github_agent.linux.pkr.hcl, images/ubuntu-focal/github_agent.ubuntu.pkr.hcl
If using a non-default VPC, there is no public IP address assigned to the EC2 instance. If you specified a public subnet, the EC2 instance won't have access to the internet without setting `associate_public_ip_address = true`.
=> feat(images): Add associate_public_ip_address variable

main.tf
our cloud security tool recommends to deny all actions via unsecured transport protocols
* added policy to deny all actions on queue with unsecured transport method
=> feat: Add SQS queue resource policy to improve security

README.md, main.tf, modules/runner-binaries-syncer/README.md, modules/runners/README.md, modules/webhook/README.md
- Avoid creation of resource if DLQ is not used
- Update all terraform docs
=> fix: Create SQS DLQ policy only if DLQ is created

modules/runners/lambdas/runners/src/aws/runners.test.ts, modules/runners/lambdas/runners/src/aws/runners.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Fixes https://github.com/philips-labs/terraform-aws-github-runner/issues/1522
=> chore: Refactor runnerServiceConfig to be an array of strings

modules/runners/lambdas/runners/src/gh-auth/gh-auth.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
Fixes #166
I tested this with our setup and it was working fine. But we only use ephemeral runners.
=> Dont delete busy runners

versions.tf
See for details #1926 
Set minimal provider to 3.50 to support source_hash for AWS S3 object.
=> fix: Set the minimal AWS provider to 3.50

modules/runners/outputs.tf, modules/runners/pool/outputs.tf
Sometimes extra policies need to be attached to roles such as for custom KMS encryption of EBS. We need to output the pool lambda role so it can be configured.
=> fix: Output the role for the pool management

modules/runners/outputs.tf, outputs.tf
As the pool is optional the output needs to take this into account and access the first instance in the list. We also must output null if not set.
=> fix: outputs for pool need to account for complexity

README.md, examples/default/main.tf, modules/runners/README.md, modules/runners/main.tf, modules/runners/variables.tf, variables.tf
The problen is most likely introduces in one of the PR's to support multiple ebs.
The following options for volumes are now supported.
- Default, create an ebs for amazon linux
- Provide explicit ebs mappings via block_device_mappings
- No ebs, set block_device_mappings to []
- Deprecated! Overwrite the default volume size by setting volume_size
close: #1954
=> fix: Volume size is ingored

modules/runners/lambdas/runners/yarn.lock
moment is a sub-dep of moment-timezone and needs to be bumped.
yarn lock file is updated to take the latest moment version
=> chore: bump moment

modules/runners/templates/start-runner.ps1
#1737 reported a bug where the userdata script tried to enable the CloudWatch Agent even though it was specified to be disabled. The problem was fixed for `start-runner.sh` in #1738, but the Powershell version has the same bug. This PR fixes the Powershell version.
=> fix(runner): Don't treat $enable_cloudwatch_agent=="false" as true in Powershell

modules/runner-binaries-syncer/runner-binaries-syncer.tf
* removed old usage of environment variable which causes an error on template interpolation
=> fix: replaced old environment variable

modules/runner-binaries-syncer/runner-binaries-syncer.tf
* fixes an error during apply on aws_s3_object when encryption is enabled
* set kms key id when encryption is enabled
* dont set unsupported etag property when encryption is enabled
=> fix: set kms key on aws_s3_object when encryption is enabled

README.md, modules/runner-binaries-syncer/README.md, modules/runners/README.md, modules/setup-iam-permissions/README.md, modules/webhook/README.md
Adding request for feedback to readme.
=> docs: Add feedback request to readme

modules/runners/policies/lambda-scale-down.json
* removed useless asterik in permission (there is no other action with prefix `DescribeInstances`)
=> fix: Remove asterik in permission for runner lambda to describe instances

modules/runners/logging.tf
Runner log paths where not updated after moving the default runner location to /opt/action-runner.
=> fix: Incorrect path of Runner logs

examples/ubuntu/templates/user-data.sh
This fixes and issue we where having where [actions/setup-python](https://github.com/actions/setup-python) was unable to install python because it didn't have access to `/opt/hostedtoolcache`. 
It seems like the issue comes from the example `user_data.sh` script setting the variable `$USER_NAME` while the `install-runner.sh` uses the variable `$user_name` to set the `/opt/hostedtoolcache` permissions
https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/templates/install-runner.sh#L55 
This also changed the user_name to "ubuntu" to match the `runner_run_as ` as option in: 
https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/examples/ubuntu/main.tf#L40
This issue seems to be related:
https://github.com/actions/setup-python/issues/459
=> fix: Update ubuntu example to fix /opt/hostedtoolcache

modules/webhook/lambdas/webhook/src/webhook/handler.ts
In webhook lambda `handler.ts` there is a misleading log that suggests that the job was queued.
When the action is not in the queued state (e.g. completed or canceled), this log may be misleading.
=> fix: Webhook lambda misleading log

README.md, docs/test-lambda-local.md, examples/prebuilt/README.md, modules/download-lambda/README.md, modules/runner-binaries-syncer/README.md, modules/runners/README.md, modules/setup-iam-permissions/README.md, modules/webhook/README.md
- improve code block highlighting in docs (530137c6c1113c9423eec08b06af461fc92a030a)
- bump download-lambda example to latest release (8bed41f7a340dec6cdeea1dafbaf1ed48397c1ba)
- change code block formatting of logo to plain (f386754ba3eaac4cdb6c1f7ffe6de816164bc61d)
=> docs: improvement of formatting in documentation

modules/webhook/lambdas/webhook/src/webhook/handler.ts
https://github.com/philips-labs/terraform-aws-github-runner/issues/2210
=> fix: Preventing that lambda webhook fails when it tries to process a installation_repositories event

modules/webhook/lambdas/webhook/src/webhook/handler.test.ts, modules/webhook/lambdas/webhook/src/webhook/handler.ts
Thanks for this awesome project! It is really useful :)
I think that `webhook` should allow run jobs in `self-hosted` runners without requiring pass all labels.
Labels are usually intended for describing capabilities (in runners) and requirements (in jobs). If I only want to require that my job is run in a `self-hosted` runner no matters what other capabilities runner have, passing only `self-hosted` label should be enough.
On the other hand, if I require to run my job in a `self-hosted` and `ubuntu` runner using these labels, but I haven't any `ubuntu` runner, it shouldn't be run.
Thank you for your time.
=> feat: Webhook accept jobs where not all labels are provided in job.

modules/runners/scale-up.tf, modules/webhook/lambdas/webhook/src/webhook/handler.test.ts, modules/webhook/lambdas/webhook/src/webhook/handler.ts, modules/webhook/webhook.tf
GitHub is not specifying if labels of runners are case senstive or not. But experiments make it clear that runners accept jobs without checking the cases of labels. This PR will ensure all labels are always set in lower case and all checks are don with lower case.
=> fix: Ignore case for runner labels.

examples/ubuntu/main.tf, examples/ubuntu/templates/user-data.sh
A fresh installation on Ubuntu 22.04 is missing iptables, which is required for rootless docker do work.
- adding iptables apt-get install list
- sorting apt-get install list
=> fix(examples): Upgrading ubuntu example to 22.04

modules/runners/lambdas/runners/src/aws/runners.ts
Seems that the allocation strategy isn't passed.
*Note: First time doing anything in type script*
=> fix(runners): Pass allocation strategy

images/windows-core-2019/github_agent.windows.pkr.hcl
Support `instance_type` variable in Windows runner image, similar to other runner images.
=> feat: Allow passing instance type when building windows image

.pre-commit-config.yaml
This fixes the problem that `pre-commit` cannot be newly configured because `git://` protocol has been shutdown in GitHub on March 15, 2022.
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
=> chore: Use `https` instead of `git` in pre-commit config

modules/runners/main.tf
AWS removed the Windows Server 20H2 AMIs on [2022-08-09](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-ami-version-history.html), causing this
module to fail when trying to lookup AMIs with that name.
=> fix(runners): Set the default Windows AMI to Server 2022

main.tf, variables.tf
This changed the default for encryption of messages on the SQS queues managed by the module. 
- By default messages will be encrypted via SSE.
- Optional users can use a custom key (CMK) to encrypt or decide to disable encryption at all.
Close: #2389
=> feat: Encrypted data at REST on SQS by default

images/windows-core-2022/bootstrap_win.ps1, images/windows-core-2022/github_agent.windows.pkr.hcl, images/windows-core-2022/windows-provisioner.ps1
This change adds an AMI for Windows Core 2022
=> feat(images): add ami for windows core 2022

README.md, main.tf, modules/runner-binaries-syncer/README.md, templates/resource-group.json
Fix for bug #2417 to remove resource group from module since we are no longer setting a predefined tag to all resources.
Tests all passed locally.
Pre commit checks updated terraform docs to include missing documentation from a recently merged pull request for S3. Happy to remove these commits and leave them for a separate pull request.
=> fix: Remove resource group from module

README.md, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock, modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts, modules/runners/lambdas/runners/yarn.lock, modules/webhook/lambdas/webhook/src/lambda.ts, modules/webhook/lambdas/webhook/src/webhook/handler.test.ts, modules/webhook/lambdas/webhook/src/webhook/handler.ts, modules/webhook/lambdas/webhook/yarn.lock
The event `check_run` was used in the module for scaling before GitHub introduced the event `workflow_job`. The workflow job event was introduced in release [0.17.0](https://github.com/philips-labs/terraform-aws-github-runner/compare/v0.16.0...v0.17.0) (2021-08-06).
Updatte the webhook / app to subscribe to workflow_job instead of check_run. In case using GHES and not having support for the workflow_job yu have to upgrade to a newer version (3.3.0+ / Dec 2021).
=> feat: Remove support check_run

modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
Removing old scale down mechanism which was used till release 0.19.0. To support migration, we kept the old mechanism. New scale down based on owner logic was introduced via PR #1065
Test via deployment
=> feat: Remove old scale down mechanism (< 0.19.0)

.github/workflows/release.yml
Replacing deprecated `set-output` to use env `$GITHUB_OUTPUT` instead.
Blogg post about deprecation:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix: replacing deprecated set-output in workflow

modules/runners/scale-up.tf
The role policy needs to use the variable so that when deployed into govcloud (or other non-default partition setup) the referenced parameter can be created and/or found.
=> fix: Use aws_partition for govcloud users in ami_id_ssm_parameter_read policy definition

README.md
Remove the beta warning for ephemeral runners. Thanks @mattsb42 for pointing out.
=> docs: Remove the beta warning from ephmeral runners

.github/workflows/terraform.yml, examples/arm64/versions.tf, examples/default/versions.tf, examples/ephemeral/versions.tf, examples/multi-runner/versions.tf, examples/permissions-boundary/setup/versions.tf, examples/permissions-boundary/versions.tf, examples/prebuilt/versions.tf, examples/ubuntu/versions.tf, examples/windows/versions.tf, modules/download-lambda/versions.tf, modules/runner-binaries-syncer/versions.tf, modules/runners/versions.tf, modules/setup-iam-permissions/versions.tf, modules/ssm/versions.tf, modules/webhook/versions.tf, versions.tf
To make it possible to refactor, and use optional defaults introduced in Terraform 1.3.x the minimal version will set to 1.3.0. This will avoid that we need later another breaking release to support the new Terraform constructs.
Only required migration is to upgrade Terraform to 1.3.x. For any 1.x version this should have minor impact.
=> chore: bump min terraform version to 1.3.0

main.tf
This PR addresses the issue #2591 where if the sqs queues are fifo, the corresponding Dead Letter queues should be fifo too.
=> fix: Updated the fifo flag for deadletter queue.

modules/multi-runner/runners.tf
Avoid validation error when `enable_runner_binaries_syncer=false`.
```
Error: Invalid value for input variable
│
│   on .terraform/modules/multi-runner/modules/multi-runner/runners.tf line 13, in module "runners":
│   13:   s3_runner_binaries = each.value.runner_config.enable_runner_binaries_syncer ? local.runner_binaries_by_os_and_arch_map["${each.value.runner_config.runner_os}_${each.value.runner_config.runner_architecture}"] : {}
│
│ The given value is not suitable for module.multi-runner.module.runners["linux-x64-default"].var.s3_runner_binaries declared at
│ .terraform/modules/multi-runner/modules/runners/variables.tf:49,1-30: attributes "arn", "id", and "key" are required.
```
=> fix(multi-runner): Default value validation error

main.tf
The variables [lambda_subnet_ids](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runner-binaries-syncer/variables.tf#L156) and [lambda_security_group_ids](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runner-binaries-syncer/variables.tf#L162) are declared in the syncer module but are not passed from the root [main.tf](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/main.tf#L257), so the syncer lambda is created without the security group ids and subnets.
=> fix: Adding missing input lambda vpc vars to syncer module

modules/runners/templates/start-runner.ps1
I'm trying out v2.0.0-next.5 after using v1.18.0 successfully, and had a problem where my Windows runners failed to start up.
Connecting to the machine with SSM and looking at `c:\UserData.log`, the problem was that an extra slash was being added at the start of SSM paths. So instead of retrieving `/github-actions-runner/whatever`, it would try to retrieve `//github-actions-runner/whatever` and fail. So this PR removes the seemingly extraneous slashes, and now my runners are working well.
It's also possible that I've misconfigured something such that `$ssm_config_path` is not supposed to start with a slash, but it does in my case. Please let me know if this might be the case.
This PR also fixes a couple of typos in the powershell start-runner script.
=> fix: Remove extraneous slashes from SSM paths, other typos

.github/workflows/release.yml
We migrating away from release via npm sementic-release to release-please Advantage is that release will be prepared via a branch and no commits to a protected branch are needed anymore.
=> refactor: Migrate to release via a PR

.github/dependabot.yml
Set different commit prefix for development and production updates
- fix(component) for production
- chore(component) for dev dependencies
=> chore: Prefix production updates with fix to trigger releases

modules/runners/lambdas/runners/src/aws/runners.ts, modules/runners/lambdas/runners/src/pool/pool.test.ts, modules/runners/lambdas/runners/src/pool/pool.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
(If preferred, this can be re-targeted to main once #2801 is merged)
It appears that Jest was replacing the `bootTimeExceeded`, possibly with a `jest.Fn()`, due to the `jest.mock('./../aws/runners')`, causing it to return undefined when called under test. The introduced changes should keep the underlying module function implementations, while mocking the functions that are needed.
Ref: https://stackoverflow.com/a/53402206
Closes #2878
=> refactor(runners): Move bootTimeExceeded to runners module

modules/multi-runner/queues.tf
Fix the problem that the setting `redrive_build_queue.enabled` was ignored.
Tested with the multirunner-example and terraform plan output.
=> fix(multi-runner): Create DLQ only if requested

modules/runners/lambdas/runners/src/modules.d.ts
Adds the strategy introduced in #2718 to the ProcessEnv of the `runners` lambda.
=> fix(runners): Add missing entry for AWS-recommended price-capacity-optimized strategy to ProcessEnv interface

README.md
Addresses the confusion in #1690 (I ran into the same mistake).
=> chore(readme): clarify cron expression in readme

modules/runners/lambdas/runners/src/aws/runners.ts
The ScaleUp lambda is dropping events when there is no capacity in the zone. This results in jobs being stalled and requiring manual cancellation.
This patch adds the `InsufficientInstanceCapacity` error code to the list of scale-up errors, allowing the built-in retry mechanism to pick up the error and not lose the event
See-Also: philips-labs/terraform-aws-github-runner#2925
=> fix(runner): Adds InsufficientInstanceCapacity to list of scaling errors

modules/runners/templates/start-runner.ps1
`start-runner.ps1` was attempting to read the `cloudwatch_agent_config_runner` parameter from the wrong place, which of course failed. This PR fixes it by making it consistent with `start-runner.sh`.
=> fix(runners): Fix path to SSM cloudwatch config parameter on Windows

main.tf, modules/multi-runner/runner-binaries.tf, modules/multi-runner/webhook.tf, modules/runner-binaries-syncer/README.md, modules/runner-binaries-syncer/runner-binaries-syncer.tf, modules/runner-binaries-syncer/variables.tf, modules/webhook/README.md, modules/webhook/variables.tf, modules/webhook/webhook.tf
Hi! 👋
This PR contains the following changes:
-  It allows webhook lambda to run inside a VPC 
-  fix a minor issue in the syncer module, when the lambda is running inside vpc AWSLambdaVPCAccessExecutionRole needs to be attached.
Updated doc.
Do not hesitate to ask if you need further details,
Thanks!
=> fix: Allow lambda inside VPC

modules/runners/templates/start-runner.ps1
Another small typo in `start-runner.ps1`, this time making the AMI id fail to appear in the "Set up job" section of the workflow log.
See the bash version of the same script, which doesn't have the typo:
https://github.com/philips-labs/terraform-aws-github-runner/blob/ef548d93e7d61b3ae3e6743a3f9d8b58ba4ee5cc/modules/runners/templates/start-runner.sh#L82
And also the GitHub Actions Runner docs, where it says it's `detail` not `details`:
https://github.com/actions/runner/blob/main/docs/adrs/0354-runner-machine-info.md
By the way, I've also modified this section of the code in our local fork to include the EC2 instance type along the the AMI ID, which is very useful because our jobs are allowed to run on a long list of different instance types. It looks like this:
Note the new "Instance …
=> fix(runners): Fix typo in .setup_info generated in start-runner.ps1.

modules/setup-iam-permissions/policies/boundary.json
This is needed in order to be able to send metrics around the disk and memory. Those were getting a 403 until this update was made.
Example error in the Cloudwatch agent logs:
```
not authorized to perform: cloudwatch:PutMetricData because no permissions boundary allows the cloudwatch:PutMetricData action
status code: 403, request id: 
```
=> fix: allow the instances to send metrics

modules/runners/policies/lambda-scale-up.json, modules/runners/pool/policies/lambda-pool.json
This should fix missing IAM permissions when running from encrypted AMI. See [this issue](https://github.com/philips-labs/terraform-aws-github-runner/issues/2927)
=> fix: Add missing IAM permissions for runners from encrypted AMI

modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/jest.config.js, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/syncer.test.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/syncer.ts, modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
AWS SDK v2 is now in maintenance mode and suggest to update to v3, see https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/
=> fix(syncer): replaced aws-sdk v2 by aws-sdk v3

images/windows-core-2022/github_agent.windows.pkr.hcl
As per AWS announcment, the current Windows base image is using Docker EE which is now sold and managed MCR under s paid subscription model. This change results in the current base image using old unmaintained version of docker even with the latest Windows base image. 
To fix this shortcoming, we are replacing the base image with ECS optimized image using Docker CE and which supposedly is better managed than the current one.
=> fix(images): Changed windows base image to Windows_Server-2022-English-Full-ECS_Optimize*

.github/workflows/update-docs.yml, CONTRIBUTING.md, README.md, examples/base/README.md
We moved recently to generate Terrafom docs on the release branch. However it would be nice to have up-to-date docs on the main branch. In the past we used pre-commit. But requires a contributor have local tools setup. Keeping pre-commit and the tf-dcos action creates a conflict.
This PR will address the issues and introducee a sub optimal solution. I could not find an option to update from a Pull Request trigger the source repo or suggest the change via a PR. 
The solution in this PR
- Run the workflow on every branch
- For the main branch (protected) create a PR
Looking up if a branch is protected is possible via the API, but this API call is not allowed by the GitHub action token. It requires a personal token with more permission. 
To run the wofklow on forks, the forked repo needs to …
=> chore(ci): fix tf-docs on PR

modules/runners/lambdas/runners/package.json, modules/runners/lambdas/runners/src/aws/runners.d.ts, modules/runners/lambdas/runners/src/aws/runners.test.ts, modules/runners/lambdas/runners/src/aws/runners.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-down.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts, modules/runners/lambdas/runners/src/scale-runners/scale-up.ts, modules/runners/lambdas/runners/yarn.lock
Updates the AWS sdk for the runners lambda's from v2 to v3
Tasks:
- Refactored types, moved types for runners to a separate file
- Tests, mocks replaces, test should be unchanged
=> fix(runners): upgrade aws sdk v2 to v3

modules/runner-binaries-syncer/main.tf
ACLs were disabled by default in April 2023:
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/
As we don't use ACLs, it's simplest to configure the bucket to not use them, which is the new recommended approach.
Fixes #3202.
=> fix: Remove deprecated use of S3 ACLs

modules/runners/templates/start-runner.sh
This shows up in the "Set up job" step
=> feat: Include instance type & availability zone in Github Action logs

modules/multi-runner/runner-binaries.tf
This is a mandatory spec.
At my company, we have some forcing capital letter prefix conventions and we are using the var.prefix for that. But the bucket name you can not use capital letters. I had to patch your module like that in order to work. I am assuming this is a harmless change that you can take advantage of that.
=> fix(multi-runner):  convertdistribution_bucket_name to lowercase

modules/runner-binaries-syncer/variables.tf
The "bucket prefix" variable should have a different validation regex than "bucket name" variable but the code uses the same. The PR fixes the issue.
Note that in root module, the regex is correct, but in "runner-binaries-syncer" sub-module, the regex is incorrect.
=> fix(syncer): S3 bucket logging prefix variable condition

modules/multi-runner/outputs.tf
It will be ideal to refer to the outputs of the multi runner module with the corresponding runner configuration key instead of array indices as it can be used to create more resources based on the use case of the runners.
As of now, there is no impact on migration to this version but we have marked the `multi-runner` outputs `runners` and `binaries_syncer` as deprecated and these shall be removed in next major upgrade.
=> fix: add more outputs to multi runners module.

modules/runner-binaries-syncer/main.tf
This change will update bucket policy to always require SSL interaction, as reported in #3277. With this change, the module will always create and attach a bucket policy. However, the previous optional force SSE policy still remains optional.
=> feat(syncer): update bucket policy to require ssl

images/linux-amzn2/github_agent.linux.pkr.hcl, images/ubuntu-focal/github_agent.ubuntu.pkr.hcl, images/ubuntu-jammy-arm64/github_agent.ubuntu.pkr.hcl, images/ubuntu-jammy/github_agent.ubuntu.pkr.hcl, images/windows-core-2019/github_agent.windows.pkr.hcl, images/windows-core-2022/github_agent.windows.pkr.hcl
Currently when packer runs an image build the security group attached to the ec2 instance has an ingress rule that allows access on port 22 from 0.0.0.0/0. In our enterprise environment this is immediately flagged in Security Hub as a critical security finding.
This change will allow packer to restrict the ingress rules of the security group it creates to the IP of the machine running packer (in our case the IP of the Github runner doing our AMI builds).
=> feat(images): Allow specifying temporary security group source IP for packer builds

modules/multi-runner/runners.tf
If `runner_additional_security_group_ids` is only set outside the multi_runner_config `coalesce(each.value.runner_config.runner_additional_security_group_ids, var.runner_additional_security_group_ids)` is coalescing an empty list (the default value for `each.value.runner_config.runner_additional_security_group_ids`) with whatever is set outside the multi_runner_config, this always results in the returned value being an empty list:
```
> coalesce([], ["sg-123456"])
tolist([])
```
Using coalescelist instead returns the first non-empty list:
```
> coalescelist([], ["sg-123456"])
[
"sg-123456",
]
```
And the `try` returns an empty list if both coalesced lists are empty (rather than throwing an error):
```
> try(coalescelist([], []), [])
[]
```
=> fix(multi-runner): Fix runner_additional_security_group_ids

.gitignore, CONTRIBUTING.md, lambdas/functions/control-plane/src/aws/runners.test.ts, lambdas/functions/control-plane/src/aws/runners.ts
Currently, volumes attached to runners are only tagged with tags specified by the AWS Launch Template. In particular, they're missing `Owner` tag, which can only be applied during "runtime".
This PR changes the way instances are created from the launch template. It adds tag specifications for the `volume` resource type to the instance creation request. With that input, the created volumes will have the same tags as the instance itself.
During the creation of this PR I noticed I had to perform a few more actions to be able to test it. I added the new instructions to the contribution guide.
I also added terraform lock file to git ignore because `terraform init` creates it and I didn't see it being committed before.
=> feat: tag runner volumes with the same tags as the instance

.github/dependabot.yml
Based on new functionality
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
=> chore: group dependencies of aws-sdk and octokit.

modules/runners/main.tf
After introducing the default value of `{state = ["Available"]}`, we missed to update the logic around the use of default filters and the custom filters.
With this change:
- If `ami_filter` is NOT changed by the root module user, it will be merged with default value of `local.default_ami` and the output will have combination of default_ami and `{state = ["Available"]}`.
- If `ami_filter` is CHANGED by the root module user with a new value of `name`, the default value will be overriden as a result of the merge operation.
- if `ami_filter` is explicitly set to null, variable validation will fail and not proceed.
=> fix: broken AMI fileter

modules/runners/templates/start-runner.ps1, modules/runners/templates/start-runner.sh
Testing Windows 2019 using multi-runner and these image scripts https://github.com/philips-labs/terraform-aws-github-runner/tree/main/images/windows-core-2019 . Installed a number of [choco packages](https://chocolatey.org/) in the AMI such as cmake, python, curl, visual studio. Ran github actions. Most of the time, the windows 2019 runners would be launched but never actually process any jobs. The jobs would be frozen forever.
Log into the server and checked runner-startup.log. Here is the output:
```
Retrieving TOKEN from AWS API
PS>TerminatingError(Invoke-RestMethod): "Unable to connect to the remote server"
Invoke-RestMethod : Unable to connect to the remote server
At C:\start-runner.ps1:21 char:8
+ $token=Invoke-RestMethod -Method PUT -Uri "http://169.254.169.254/lat ...
+ …
```
=> fix: Retry aws metadata token download

modules/multi-runner/variables.tf
After changed to defaults for AMI filter, changes were not applied to the multi-runners defaults
=> fix: add state for multi-runner default ami-filter

.github/workflows/release.yml
=> chore: update release build to node 18

modules/runners/templates/start-runner.sh
#3393 broke (Ubuntu) ephemeral runners when `enable_jit_config = true`.
The introduction of `enable_jit_config` came with an update of script `/opt/start-runner-service.sh` that required it to run in a shell with *double bracket* keyword support:
https://github.com/philips-labs/terraform-aws-github-runner/blob/cfbcc944fc183b481caaee323e7832ec1964eb54/modules/runners/templates/start-runner.sh#L123-L129
Currently, script `/opt/start-runner-service.sh` is chmoded executable but has no shebang.
In Ubuntu, this results in `nohup` running it with plain `sh`, hence the following error log:
```log
Starting the runner as user ubuntu
Starting the runner in ephemeral mode
/opt/start-runner-service.sh: 4: [[: not found
Starting without JIT config
An error occurred: Not configured. Run config.(sh/cmd) …
```
=> fix(runners): ensure `/opt/start-runner-service.sh` is run with Bash

.gitignore, .vscode/gh-runners.code-workspace, lambdas/functions/control-plane/src/scale-runners/scale-down.test.ts
- fix for randomly failing unit test after merging #3375
- add workspace config for vscode
- increase coverage
=> chore: fix test and add vscode workspace config

modules/multi-runner/variables.tf, modules/runner-binaries-syncer/variables.tf, modules/webhook/variables.tf
Top level module has set log retention to 180 days. This PR's ensure that each module is applying the same default.
=> fix: set log retention in each module by default to 180

examples/multi-runner/templates/runner-configs/windows-x64.yaml, modules/runners/main.tf
Replace Window AMI by  Windows_Server-2022-English-Full-ECS_Optimized-*
close #3423
=> fix: Replace defaul AMI for WIndows

modules/multi-runner/runners.tf, modules/multi-runner/variables.tf
Cloud config can only set for all multi-runners and not per runner. 
Add option to set the cloud config per runner.
=> feat: support for cloudwatch config on multi-runners

modules/runners/scale-up.tf
Fixed the problem of AWS not being able to run correctly in China due to partition errors
=> fix: missing partion in ARN to support China or govCloud

modules/multi-runner/runners.tf, modules/multi-runner/variables.tf, modules/runners/main.tf, modules/runners/variables.tf
Fixes: https://github.com/philips-labs/terraform-aws-github-runner/issues/2988
Adds ebs_optimized parameter for ec2 instances.
Currently this defaults to false to keep it in line with the previous behavior.
=> feat: Add ebs_optimized option

README.md, docs/additional_notes.md
Explanation of issue: There are many popular CI systems that exist out in the world, not only GitHub Actions. It's probably common enough that a developer comes to this project and needs to configure the Terraform runners with GitHub Actions, while also having in their mind how other systems operate, and those may be different. It's easy to imagine all runner labels must match all job labels. Other systems are designed that way. To quickly solve the problem this is a sort of cheatsheet.
=> docs: Document using labels with self-hosted runners

lambdas/functions/webhook/jest.config.ts, lambdas/functions/webhook/src/webhook/handler.test.ts, lambdas/functions/webhook/src/webhook/handler.ts, modules/webhook/variables.tf
When using the mult-runner with an exact match set to `true` worklfows events with an empty array of labels matches the first matcher. This cause not intented runners are created. This change avoids jobs with no labels ar accepted.
The exactMatch is some bagage we ccarry from the past. I have aaded a set of unit tests to show how the match is working. We should think about removing the switch.
=> fix(webhook): Avoid jobs are accepted without labels

modules/runners/main.tf
Runner security group is currently open.
This patch removes the default ingress rule security group to deny everything.
More info on [this documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#removing-all-ingress-and-egress-rules).
=> fix: restrict runner security group to only ingress

CONTRIBUTING.md
Update Slack link in CONTRIBUTING 
Closes: #3576
=> docs: Correct link to slack

modules/runners/ssm-housekeeper.tf
Roles names can grow quite long for multi runners. this beacause the prefix. THe PR shorten the role name which is a quick fix.
=> fix: shorten role name for ssm housekeeper

modules/webhook-github-app/bin/update-app.sh, modules/webhook-github-app/main.tf
* Change to `webhook-github-app` to use single character options
The module fails silently, but bash `getopts` does not support multicharacter options this changes that to use single character options instead.
* fixes: #3556
* https://stackoverflow.com/questions/3975004/how-to-make-a-multi-character-parameter-in-unix-using-getopt
* https://unix.stackexchange.com/questions/684717/how-to-use-getopts-in-bash
* https://stackoverflow.com/questions/402377/using-getopts-to-process-long-and-short-command-line-options
=> fix(examples): webhook-github-app multiple character args

examples/multi-runner/README.md
There was an extra backtick so code wasn't being displayed properly.
=> docs: markdown docs example multi-runner

lambdas/functions/webhook/src/ConfigResolver.ts, lambdas/functions/webhook/src/sqs/index.test.ts
Fixed the issue with workflow job queue misconfiguration introduced during the PR https://github.com/philips-labs/terraform-aws-github-runner/commit/f2112ea466af0293f237fd54b38b400c10611b2f
=> fix: workflow job event queue misconfiguration.

examples/default/.terraform.lock.hcl, modules/multi-runner/main.tf
The multi runner module is adding on two places the default labels like `self-hosted`, `os` and `arch`. The PR ensures the default labels are only added in [`multi-runner/runners.tf`](https://github.com/philips-labs/terraform-aws-github-runner/blob/4f257f9ff643e1f31e597a15dd9a0a65afbdc605/modules/multi-runner/runners.tf#L48)
=> fix(multi-runner): remove renundant default labels

images/ubuntu-jammy-arm64/github_agent.ubuntu.pkr.hcl, images/ubuntu-jammy/github_agent.ubuntu.pkr.hcl
This PR fixes the exact same issue as: https://github.com/philips-labs/terraform-aws-github-runner/pull/2214
but for ubuntu jammy instead.
Using the aws cli we can see Canonical have published eks images which match the old ami filter:
```
$ aws ec2 describe-images --owners "099720109477" --filters "Name=name,Values=*/ubuntu-jammy-22.04-amd64-server-*" "Name=root-device-type,Values=ebs" "Name=virtualization-type,Values=hvm" --query 'reverse(sort_by(Images,&CreationDate))[:10].{id:ImageId,date:CreationDate,name:Name}'
[
{
"id": "ami-076c5927ad06134ea",
"date": "2024-02-01T14:32:11.000Z",
"name": "ubuntu-eks/k8s_1.29/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240201"
},
{
"id": "ami-01daded1d6569f09c",
"date": "2024-01-31T23:50:34.000Z",
"name": …
```
=> fix(images): avoid wrong AMI selected for ubuntu jammy

lambdas/functions/termination-watcher/src/lambda.test.ts, lambdas/functions/termination-watcher/src/termination-warning.ts
Changed log level to debug in case no match. Deploying the lambda multiple times in a single aws account will create unrelated warning logs otherwise.
=> fix: change log level for termination watcher if no match

modules/runners/scale-up.tf
Fixes https://github.com/philips-labs/terraform-aws-github-runner/issues/3886
=> fix: Typo in env vars for scale-up lambda

modules/setup-iam-permissions/policies/deploy-boundary.json
`setup-iam-permissions`: add missing `iam:TagInstanceProfile` required for `aws_iam_instance_profile "runner"`
The `aws_iam_instance_profile` resource in https://github.com/philips-labs/terraform-aws-github-runner/blob/74471de59ac97748581612efa62c3950344916f4/modules/runners/policies-runner.tf#L11-L16 requires the `iam:TagInstanceProfile` permission.
=> fix: adding missing permissions to boundaries

lambdas/functions/control-plane/src/scale-runners/scale-up.test.ts, lambdas/functions/control-plane/src/scale-runners/scale-up.ts, lambdas/libs/aws-ssm-util/src/index.ts, modules/runners/policies/instance-ssm-parameters-policy.json, modules/runners/policies/lambda-scale-up.json, modules/runners/pool/policies/lambda-pool.json
Previously, EC2 instances could read other instances' tokens (via path .../tokens/...) from SSM parameters. This PR restricts access to only read / delete tokens owned by the instances
=> feat: Restrict instance SSM permissions

README.md, main.tf, variables.tf
feat: add variable to configure ebs optimization for runner instances
=> feat: add variable to configure ebs optimization for runner instances

.github/workflows/stale.yml
Incrase stale time to 3 months. Since are not able at this moment to keep up-to-date with PRs and issues.
=> chore: increase time to mark issues/prs as stale

modules/webhook/webhook.tf
We currently indicate that this feature is disabled by setting the env var to an empty string. But instead we could omit it, to avoid polluting the environment, and causing a warning to be logged.
This is a companion to #3942. That one stops the warning mentioned, this one fixes the original cause by not setting the env var in the first place. Both could be merged, ideally.
=> fix(webhook): Don't set `${SQS_WORKFLOW_JOB_QUEUE}` to empty string

lambdas/functions/webhook/src/ConfigResolver.ts, lambdas/functions/webhook/src/sqs/index.test.ts, lambdas/functions/webhook/src/sqs/index.ts
Right now the Terraform module is causing `${SQS_WORKFLOW_JOB_QUEUE}` to be set to an empty string. Since we pass this through currently, and explicitly check for `!== undefined` - not any falsy value - we end up trying to send to an empty queue and logging a warning.
Doesn't break anything, but it's noisy in the logs.
Fix this by checking for any falsy value instead, and also using `||` instead of `??` when setting the variable in the first place, so an empty string ends up as `undefined`. Also, modify the testsuite to check for the `SQS` being created at all, since that happens earlier on and reproduces the failure.
This is a companion to #3943. This one stops the warning, and that one fixes the original cause by not setting the env var in the first place. Both could be merged, ideally.
=> fix(webhook): Don't log warning when secondary job queue is empty

lambdas/functions/control-plane/src/aws/runners.ts, lambdas/functions/control-plane/src/lambda.ts
In case the AMI ID Parameter was set to something that did not exist, it would produce an obscure error: "message": "Ignoring error: UnknownError".
Now it produces better error messages:
"message": "Ignoring error: Error: Failed to lookup runner AMI ID from SSM parameter: /github-action-runners/staging/ubuntu-x64/runners/config/ami-id,\n       ParameterNotFound: UnknownError",
Signed-off-by: Brend Smits <brend.smits@philips.com>
=> fix: improve logging when there is an error retrieving ssm parameters

modules/runners/templates/start-runner.sh
Remove not used job web ook that was logging potential sensitive information.
close #3980
=> fix: remove job start hook with senstive information

lambdas/functions/control-plane/jest.config.ts, lambdas/functions/control-plane/package.json, lambdas/functions/control-plane/src/gh-auth/gh-auth.ts, lambdas/yarn.lock
Adding explicit logging for GitHub reate limits. No retries implemented. Only for abuse retrying seems an option. In other cases a retry will take to long given lambda timeouts taken into accont.
=> fix: add warnings to log for GitHub rate limits

lambdas/functions/control-plane/src/scale-runners/scale-down.test.ts, lambdas/functions/control-plane/src/scale-runners/scale-down.ts
The test structure and magic for scaling down makes it hard to make any change. This PR refactor the tests cases in suche way
- only global default mocking
- per test explicit mocking
- per test setup test data, avoiding global data mesh
Test coverage is 100% for scale-down.
Note: Codescene warnings are not new, but a bit the fact of how jest works
=> refactor: scale down tests

modules/webhook/main.tf
We want to add a lambda authenticator to webhook API endpoint to restrict requests by source IP address. To achieve this, the following two options are possible:
1. add attributes to pass authorizer resource information to this module,
2. or simply ignores changes related to authorizer of `aws_apigatewayv2_route` resource,
However, 1. requires all informations to create `aws_apigatewayv2_authorizer` and `aws_lambda_permission`, this is little bit need consideration. Option 2. is, of cource, needs resouce update by hand, however, the very simple to achieve by ignoring attribute changes.
This PR aims to implement option 2.
=> feat(webhook): Enable authorizer assignment to webhook

.github/dependabot.yml, lambdas/functions/termination-watcher/src/lambda.ts, lambdas/functions/termination-watcher/src/termination-warning.test.ts, lambdas/functions/termination-watcher/src/termination-warning.ts, lambdas/libs/aws-powertools-util/package.json, lambdas/libs/aws-powertools-util/src/metrics/index.ts, lambdas/libs/aws-powertools-util/src/metrics/metrics.test.ts, lambdas/libs/aws-powertools-util/src/tracer/index.ts, lambdas/yarn.lock
AWS powetertools v1 will be end of life on Sept 1st 2024. Secondly upgrade to v2 is required to move to ESM
See https://docs.powertools.aws.dev/lambda/typescript/latest/upgrade/
=> fix: upgrade aws powertools to v2

modules/multi-runner/variables.tf
`enable_runner_on_demand_failover_for_errors` isn't defined as an attribute for the var and isn't referenced anywhere either.
=> docs: Correct multi-runner var description

CONTRIBUTING.md
The process of updating the Terraform module documentation is now run on the `main` branch ([example](https://github.com/philips-labs/terraform-aws-github-runner/pull/3919)), so it no longer needs to be run on forked repositories (it also requires credentials for the GitHub App).
As per @npalm's [comment](https://github.com/philips-labs/terraform-aws-github-runner/pull/4063#issuecomment-2286734539), I'm removing this reference, to prevent any confusion for new contributors.
=> docs: Remove outdated instruction from contribution guide

modules/runners/job-retry.tf
Object key and object version not passed into job retry module.
=> fix: missing lambda s3 key and version for job retry

modules/runners/pool/main.tf
In #4063 PR the EventBridge Schedule is introduces. For schedule groups a name prefix is used. But since the name for the name prefix is already unieque the name can be used instead of prefix to avoid too long prefix names (30 chars plus).
=> fix: use name instead of name prefix to avoid too long names

modules/runners/job-retry.tf
Zip file is not passed to job-retry module
fix #4078
=> fix: pass lambda zip file to job retry feature

modules/ami-housekeeper/main.tf
Created even rule for ami is static, it missing a dynamic element (prefix) to ensure unique resources.
=> fix: add missing prefix to ami cleanur for event rule

modules/runners/README.md, modules/runners/job-retry/main.tf, modules/runners/scale-up.tf
- resource incorrect named (copy / paste)
- typo in queue name for rety
=> fix: job retry resource and queue naming

docs/index.md
Fix 'we' typo in index.md for the Detailed design area in documentation.
=> chore: Update index.md typo

docs/modules/runners.md, mkdocs.yaml
Make explicit what is the main and what is a submodule.
=> docs: explicit naming submodules

modules/runners/job-retry.tf
The environment variable for the retry lambads is not set due to missing to pass the value to the inner terraform module. This fix remedies that.
=> fix: missing GHES URL for the retry lambda

modules/download-lambda/README.md, modules/download-lambda/versions.tf, modules/webhook/README.md, modules/webhook/versions.tf
This PR removes the minor version lock for modules to align them with others.
Kudos to [rishta](https://github.com/rishta) for spotting this issue and trying to help us resolve it
=> chore: fix null version to major

examples/default/main.tf, modules/webhook/eventbridge/README.md, modules/webhook/eventbridge/dispatcher.tf
Dispatcher for EventBridge does not have access to sqs queueu for publish workflow job event.
=> fix(webhook): add missing permission to workflow job queue (EventBridge)

examples/multi-runner/main.tf
I don't see this being used, and the only example available, it lead to confusion
=> fix: remove unused example spot_instance_termination_watcher

modules/webhook/direct/README.md, modules/webhook/direct/main.tf, modules/webhook/direct/webhook.tf, modules/webhook/eventbridge/README.md, modules/webhook/eventbridge/dispatcher.tf, modules/webhook/eventbridge/main.tf, modules/webhook/eventbridge/webhook.tf
Currently we use the lifecyle trigger in Terraform to enforce lambda reload. Unwanted side-effect is resources getting destroyed. Even leading to the lambda trigger for the dispatch functiong not getting re-created.
Instead of adding the lifecyle event to multiple resources, the version of the SSM paramater is added to environment variables of the Lambda to enforce [cold start](https://docs.aws.amazon.com/lambda/latest/operatorguide/execution-environments.html) after updates. 
- default example
- multi runner, changing labels
=> fix: trigger cold start dispatcher after update SSM parameters

modules/webhook/eventbridge/dispatcher.tf
Update dispatch to only subscribe for queued events instead for all events.
=> fix: dispatch only queued events to runners

lambdas/package.json, lambdas/yarn.lock
For some reasn the nx build was borken on mac. Fixed by ensuring all nx dependency are aligned (yarn dedupe) and added a nx group for dependabot.
=> chore: add nx group, and fix broken nx on mac

README.md
=> docs: Add annoucements to move repo

main.tf, variables.deprecated.tf
Hi. Thanks for this module.
I come from a CDKTF shop. CDKTF basically has a code generator based on the HCL code which generates the appropriate objects and types.
TypeScript uses camel case as default convention for symbols so that code generator produces invalid code as both the current `runners_scale_up_lambda_memory_size` and the legacy `runners_scale_up_Lambda_memory_size` are converted to the same camel cased string and the TypeScript compiler rejects that code when imported as it contains duplicate symbols.
Removing this deprecated variable enables the CDKTF users who run into this problem to successfully use this module.
This is a breaking change but I don't know for how long you do keep deprecated vars.
=> fix!: remove deprecated runners_scale_up_Lambda_memory_size as it breaks CDKTF
