README.md
examples/default/main.tf
examples/permissions-boundary/main.tf
kms.tf
main.tf
modules/download-lambda/README.md
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
modules/runners/README.md
modules/runners/encrypt.tf
modules/runners/lambdas/runners/src/scale-runners/kms/index.ts
modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
modules/runners/lambdas/runners/yarn.lock
modules/runners/scale-down.tf
modules/runners/scale-up.tf
modules/runners/variables.tf
modules/setup-iam-permissions/policies/boundary.json
modules/setup-iam-permissions/policies/deploy-boundary.json
modules/setup-iam-permissions/policies/deploy-policy.json
modules/webhook/README.md
modules/webhook/lambdas/webhook/package.json
modules/webhook/lambdas/webhook/src/kms/index.ts
modules/webhook/lambdas/webhook/src/webhook/handler.test.ts
modules/webhook/lambdas/webhook/src/webhook/handler.ts
modules/webhook/lambdas/webhook/yarn.lock
modules/webhook/variables.tf
modules/webhook/webhook.tf
variables.tf

#34 - encrypt secrets via KMS

---

README.md

Description of the Change
- Updated module version in README
- Fixed wrong .zip.zip extension in README
Release Notes
- N/A

Minor README fix/update

---

examples/default/main.tf
examples/default/providers.tf
examples/default/variables.tf
examples/default/vpc.tf
examples/permissions-boundary/main.tf
examples/permissions-boundary/providers.tf
examples/permissions-boundary/variables.tf
examples/permissions-boundary/vpc.tf
modules/runner-binaries-syncer/variables.tf
modules/runners/scale-down.tf
modules/runners/variables.tf
modules/setup-iam-permissions/main.tf
modules/setup-iam-permissions/variables.tf
outputs.tf
variables.tf

Introduces consistency where newlines are used.
- Introduces consistency where newlines are used.

be consistent with new lines

---

.ci/build.sh
README.md
examples/default/README.md
examples/default/main.tf
examples/permissions-boundary/setup/main.tf
modules/runner-binaries-syncer/runner-binaries-syncer.tf
modules/runners/README.md
modules/runners/variables.tf
modules/setup-iam-permissions/README.md
modules/setup-iam-permissions/variables.tf
modules/webhook/README.md
modules/webhook/variables.tf
modules/webhook/webhook.tf
variables.tf

Fixes several typos in variable descriptions and documentation.
- Fixes several typos in variable descriptions and documentation.

fix various typos

---

README.md

fix module version in code samples for README.MD
fix module version in code samples for README.MD

fix  module version in readme code samples to the latest

---

modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/handler.ts

Add explicit type info to support resolve in typsescript 4.1+

Updates to support typescript 4.1

---

CHANGELOG.md
modules/runners/policies/instance-ssm-parameters-policy.json

Add ssm:GetParameter to runner-ssm-parameters

---

main.tf

Fix #465 introduced via PR #412

fix: for invalid configuration

---

variables.tf

* swapping description of scale up/scale down time variable description

fix: Swap scale up/scale down timeout description

---

modules/runners/lambdas/runners/src/scale-runners/gh-auth.test.ts
modules/runners/lambdas/runners/src/scale-runners/gh-auth.ts

- Adds `mediaType` to correct location
- Tests that `mediaType` is added for GHES

fix(ghes): Corrects preview option

---

README.md

:wave: @npalm,
I've spent a bit of time to help people find self-hosted GitHub Action solutions, I think its going to be huge and wanted to help people to discover them.
I am following your project for some time, and am happily using it, so I added it to the list https://github.com/jonico/awesome-runners 🏃  
I have also added a badge (if you are interested):
[![awesome-runners](https://img.shields.io/badge/listed%20on-awesome--runners-blue.svg)](https://github.com/jonico/awesome-runners)
Keep up the great work 👍

Add your project to awesome-runners list

---

modules/runner-binaries-syncer/runner-binaries-syncer.tf

Resolves SecurityHub Violation.     Access needed to be locked down to the account in question.

Account Source Account

---

modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
modules/runners/lambdas/runners/package.json
modules/runners/lambdas/runners/yarn.lock
modules/webhook/lambdas/webhook/package.json
modules/webhook/lambdas/webhook/yarn.lock

Revert vercel/ncc back to version 0.27.0

fix: apply patch for broken scale up lambda #980

---

README.md
main.tf
variables.tf

feat: make delay of webhook event configurable

---

.github/workflows/lambda-runner-binaries-syncer.yml
.github/workflows/lambda-runners.yml
.github/workflows/lambda-webhook.yml
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/handler.test.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
modules/runners/lambdas/runners/package.json
modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
modules/webhook/lambdas/webhook/package.json
modules/webhook/lambdas/webhook/yarn.lock

I added a question in the ticket, if the tests should also be formatted and format-checked. If so, please indicate, and I will update this pull request.

feat: add format checking for lambdas in CI (#899)

---

modules/runners/lambdas/runners/src/lambda.ts
modules/runners/lambdas/runners/src/scale-runners/scale-up.ts

- Fixes output of events
- Adds additional debug logging at possible failure point during scale up

fix(logging): Additional Logging

---

modules/runners/lambdas/runners/src/scale-runners/cache.ts
modules/runners/lambdas/runners/src/scale-runners/scale-down.ts

The class is not being re-created between runs. Clearing each map appears to be necessary to avoid stale data.

fix(scale-down): Clearing cache between runs

---

modules/runner-binaries-syncer/variables.tf

Fixes https://github.com/philips-labs/terraform-aws-github-runner/issues/1310

feat: add validation to distribution_bucket_name variable

---

modules/runners/policies-runner.tf

Fixes: https://github.com/philips-labs/terraform-aws-github-runner/issues/1340
This is a **breaking** change as it will impact people's IAM trust relationships. Please do say if you don't feel comfortable with it, you have my reasoning on the raised issue for why I've raised this PR in this way.

feat: reducing verbosity of role and profile names

---

.github/workflows/release.yml

Add provenance file for releases.
SLSA level 1

chore: Add provenance file

---

modules/ssm/versions.tf

Adding missing required providers for submodule

fix: Add required providers to module ssm

---

outputs.tf

https://github.com/philips-labs/terraform-aws-github-runner/issues/1443

fix: add runners binaries bucket as terraform output

---

modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/jest.config.js
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/lambda.test.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/lambda.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/syncer.test.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/syncer.ts

Changes applied in PR #1478 are not working properly.
Function `sync` is not triggered via the Lambda handler. Cause uploadS3 function was not awaited. Also the s3upload function was not tested. 
- add await
- fix tests
- adjust coverage criteria

fix: Download lambda

---

modules/runners/templates/start-runner.sh

fix: add --preserve-env to start-runner.sh to enable RUNNER_ALLOW_RUNASROOT

---

modules/runners/templates/install-runner.sh
modules/runners/templates/start-runner.sh

Remove the now unused export from the install file.

fix: remove export from install script.

---

modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/.prettierrc
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/lambda.test.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/lambda.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/local.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/modules.d.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/syncer.test.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/syncer.ts
modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock

Auto format imports for typescript with prettier.

chore(runners-binaries-syncer): Auto format imports

---

.github/workflows/release.yml
.release/package.json
.release/yarn.lock

Upgrade semantic release and pllugins to latest versions

chore(ci) Upgrade semantic release and plugins

---

images/start-runner.sh

Fixes https://github.com/philips-labs/terraform-aws-github-runner/issues/1627

fix(images): use new runner install location

---

.github/workflows/packer-build.yml
images/linux-amzn2/github_agent.linux.pkr.hcl

Add missing RUNNER_ARCHITECTURE variable to packer
close: #1646

fix(packer): Add missing RUNNER_ARCHITECTURE for amazn-linux2

---

CONTRIBUTING.md
README.md

Found some grammar errors and typos whilst reading the documentation

fix(docs): Fix grammar errors and typos

---

images/linux-amzn2/github_agent.linux.pkr.hcl
modules/runners/main.tf

Upgraded the Amazon Linux base AMI to avoid errors mentioned in #1811

fix(runners): Upgrade Amazon base AMI to Amazon Linux 2 kernel 5x

---

images/linux-amzn2/github_agent.linux.pkr.hcl
images/ubuntu-focal/github_agent.ubuntu.pkr.hcl
images/windows-core-2019/github_agent.windows.pkr.hcl

This can be used to install additional software or to customize anything else for the final AMI

feat: Add variable to specify custom commands while building the AMI

---

modules/runners/main.tf

For issue: https://github.com/philips-labs/terraform-aws-github-runner/issues/1769

feat(runners): Add possibility to not create ebs

---

modules/runners/pool.tf

fix: Retention days was used instead of kms key id for pool

---

README.md

Update docs to explicitly call out webhook event `content-type`.

docs: ensure webhook event content-type is `application/json`

---

.github/workflows/semantic-check.yml

fix: Avoid non semantic commontes can be merged.

---

.github/workflows/stale.yml

Added a stale workflow to help manage issues that become stale.

ci: Added a stale issue/pr workflow

---

.github/workflows/packer-build.yml
.github/workflows/release.yml
.github/workflows/terraform.yml
.releaserc.json

Refactor the master branch to main
After merge

chore: Refactor master to main branch

---

modules/runner-binaries-syncer/runner-binaries-syncer.tf

fixes #2105 
@julada Here is the PR to fix S3 object trigger when server_side_encryption algorithm type is AES256

fix: added server_side_encryption key in resource aws_s3_object

---

modules/runners/main.tf

Add the `s3_location_runner_distribution` variable as expandable variable for the `userdata_template`. Although the native module will not need this variable to be expand for `userdata_template`, it is much easier for users that use custom `userdata_template`.

feat: add s3_location_runner_distribution var as expandable for userdata

---

MAINTAINERS.md

Added @ScottGuymer @GuptaNavdeep1983 
Removed @gertjanmaas

chore: Update maintainers

---

README.md

I just noticed this sentence was missing a words while reading the readme.md. Thanks for your good work.

docs: Added a missing word

---

main.tf

PR #2736 broken the default module by not repecting the change label type

fix: Main module broken after supporting multiple labels 

---

examples/multi-runner/main.tf

Fix for https://github.com/philips-labs/terraform-aws-github-runner/issues/2845.

docs(examples): fix multi runner runner label in example

---

modules/runners/README.md
modules/runners/lambdas/runners/src/pool/pool.ts
modules/runners/policies-lambda-common.tf
modules/runners/pool.tf
modules/runners/pool/main.tf
modules/runners/pool/variables.tf
modules/runners/scale-up.tf

fix(pool): ensure pool top up respects var.ami_id_ssm_parameter_name

---

README.md

Single character addition. 
Side Note: I have no idea what the Semantic Commit Message wants from me. I have the PR title correct. It may be broken. If it is not, it sure is not making any friends with me.

docs: ultra tiny typo fix

---

images/ubuntu-focal/github_agent.ubuntu.pkr.hcl
images/ubuntu-jammy-arm64/github_agent.ubuntu.pkr.hcl
images/ubuntu-jammy/github_agent.ubuntu.pkr.hcl

Wait for cloud-init to be finished before calling apt.
https://github.com/philips-labs/terraform-aws-github-runner/issues/3103
Co-authored by: https://github.com/fknop that found the solution

fix(images): wait for cloud-init to be done before updating packages

---

modules/webhook/policies/lambda-publish-sqs-policy.json
modules/webhook/policies/lambda-ssm.json
modules/webhook/webhook.tf

see https://github.com/philips-labs/terraform-aws-github-runner/pull/3126

fix(webhook): add required permission to SQS message producer

---

examples/multi-runner/main.tf
examples/multi-runner/templates/runner-configs/linux-arm64.yaml
examples/multi-runner/templates/runner-configs/linux-x64-ubuntu.yaml
examples/multi-runner/templates/runner-configs/linux-x64.yaml
examples/multi-runner/templates/runner-configs/windows-x64.yaml

The example shows how runner configurations can be configured in Yaml files.
This has the following advantages:
- Compacter files for better readability
- Possibility to use CODEOWNERS file on the different configurations.

chore(examples): multi-runner example with separate configuration files

---

lambdas/tsconfig.json

Ensure lambda zip only contains index.js

chore(ci): fix lambda dist

---

lambdas/functions/control-plane/src/scale-runners/scale-up.ts

Updated the code to fix the broken lambda from previous PR.

fix: scale up lambda build issue.

---

modules/runners/templates/start-runner.sh

Adding more thorough logic to fully retry the aws metadata token download, on Linux.   Continuing https://github.com/philips-labs/terraform-aws-github-runner/pull/3292. See explanation there.
I have tested and it works, however Ubuntu usually succeeds. We will observe further how this goes or if more changes are needed.

fix(runners): retry aws metadata token download on Linux

---

examples/ephemeral/.terraform.lock.hcl
examples/ephemeral/README.md
examples/ephemeral/main.tf
examples/ephemeral/variables.tf
examples/multi-runner/main.tf
examples/multi-runner/providers.tf

- fix resource taging in mult runner example
- align ephemeral example with default and mult-runner

chore: fix resource tags for multi-runner example

---

examples/multi-runner/templates/runner-configs/linux-arm64.yaml
examples/multi-runner/templates/runner-configs/linux-x64-ubuntu.yaml
examples/multi-runner/templates/runner-configs/linux-x64.yaml
examples/multi-runner/templates/runner-configs/windows-x64.yaml
modules/multi-runner/README.md

docs: Fix delay_webhook_event variable usage in examples

---

lambdas/functions/ami-housekeeper/package.json
lambdas/functions/control-plane/package.json
lambdas/functions/gh-agent-syncer/package.json
lambdas/functions/termination-watcher/package.json
lambdas/functions/webhook/package.json
lambdas/libs/aws-ssm-util/package.json
lambdas/yarn.lock

- Ingore major updates for dependencies not updatable (powertools, octokit/webhoks)
- Update all dependencies
- Regenerate lock file, due to coruption

fix: update dependencies

---

lambdas/functions/ami-housekeeper/package.json
lambdas/functions/control-plane/package.json
lambdas/functions/gh-agent-syncer/package.json
lambdas/functions/termination-watcher/package.json
lambdas/functions/webhook/package.json
lambdas/libs/aws-ssm-util/package.json
lambdas/yarn.lock

Release 5.10.2 is borken caused by PR #3867. This PR is reverting the change
fix #3870, #3883

fix: revert depedency update / broken release 5.10.2

---

lambdas/functions/control-plane/src/aws/runners.ts
lambdas/functions/control-plane/src/scale-runners/scale-down.ts

These changes make it easier to debug the scale down lambda to diagnose problems

chore: improve logging in scale down lambda

---

lambdas/functions/control-plane/src/pool/pool.ts
lambdas/functions/control-plane/src/scale-runners/scale-up.ts

chore(typo): Fixing 'instanceTargetCapacityType' typo

---

modules/webhook-github-app/variables.tf

Resolves https://github.com/philips-labs/terraform-aws-github-runner/issues/4012

fix: mark github_app variable as sensitive

---

.github/workflows/osv-scanner.yml

Add OSV scanner to check for security issues.

chore: add osv scanner

---

lambdas/functions/webhook/src/webhook/index.ts

Webhook result message contains twice successfully

fix(webhook): result message webhook
